### ISSUE TITLE
wavecheckerが見つからない

### ISSUE THREAD

**Issue by murnana** [HomuraShakuishi/unity_study#10]
murnana/unity_study_with_RyuTatsu#17 にも書いたように、wavecheckerのクラスが書かれたスクリプトが見つからない。
コミットは無視リストに書いてある物以外すべて入れよう…

**Comment by HomuraShakuishi** [comment]
プロジェクトファイルごと放り込んでいる以上、無いファイルはありえないと思う
もしくは、無視リスト自体に弾かれている
手元のGitHubフォルダには中身があることを確認している

**Comment by HomuraShakuishi** [comment]
新しく作ったスクリプトは随時追加してからコミット、プッシュしなきゃいけないのね　知らんかったわ
