### ISSUE TITLE
やったこと、わからないこと

### ISSUE THREAD

**Issue by HomuraShakuishi** [HomuraShakuishi/unity_study#8]
やったこと

.gitignoreの場所をshootingstudyフォルダの中に移動
今日の成果(shooting game)をドラッグ&ドロップでそのまま上書き、コミット&プッシュ

わからないこと

上書きしたあと、上書きをする前のデータを見る方法

**Comment by HomuraShakuishi** [comment]
追記
更新の文を 変更#1 としてコミットした

何が変わったかわからない

**Comment by murnana** [comment]
> 上書きしたあと、上書きをする前のデータを見る方法

TotoiseGitなら…
右クリック→TotoiseGit→ログを表示


> 更新の文を 変更#1 としてコミットした

https://github.com/HomuraShakuishi/unity_study/pull/1 にリンクが張られている

**Comment by murnana** [comment]
@HomuraShakuishi 終わったらissueのCloseをお願いします
(Commentの隣にあるボタン。
そのまま押してもいいし、
コメントを書いてから押すと、コメント投稿と同時にCloseできる)

**Comment by murnana** [comment]
最新のリポジトリになっていないぞい
.gitignore　移動されていない
